django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path
from sakila import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path("act", views.act),
    path("show", views.show_actor),
    path("edit/<int:id>", views.edit_actor),
    path("update/<int:id>", views.update_actor),
    path("delete/<int:id>", views.destroy_actor),

    path("flm", views.flm),
    path("film_show", views.show_film),
    path("film_edit/<int:id>", views.edit_film),
    path("film_update/<int:id>", views.update_film),
    path("film_delete/<int:id>", views.destroy_film),

]

django_app/sakila/models.py
from django.db import models


# Create your models here.
class Actor(models.Model):
    actor_id = models.PositiveSmallIntegerField(primary_key=True)
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    last_update = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'Actor'


class Film(models.Model):
    film_id = models.PositiveSmallIntegerField(primary_key=True)
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    release_year = models.TextField(blank=True, null=True)  # This field type is a guess.
    language = models.ForeignKey('Language', models.DO_NOTHING)
    rental_duration = models.PositiveIntegerField()
    rental_rate = models.DecimalField(max_digits=4, decimal_places=2)
    length = models.PositiveSmallIntegerField(blank=True, null=True)
    replacement_cost = models.DecimalField(max_digits=5, decimal_places=2)
    rating = models.CharField(max_length=5, blank=True, null=True)
    special_features = models.CharField(max_length=54, blank=True, null=True)
    last_update = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'Film'


class FilmActor(models.Model):
    actor = models.ForeignKey('Actor', models.DO_NOTHING, primary_key=True)
    film = models.ForeignKey('Film', models.DO_NOTHING)
    last_update = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'film_actor'
        unique_together = (('actor', 'film'),)


class Language(models.Model):
    language_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    last_update = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'language'

django_app/sakila/forms.py
from django import forms
from .models import *

class ActorForm(forms.ModelForm):

    class Meta:
        model = Actor
        fields = "__all__"

class FilmActorForm(forms.ModelForm):

    class Meta:
        model = FilmActor
        fields = "__all__"

class FilmForm(forms.ModelForm):

    class Meta:
        model = Film
        fields = "__all__"

class LanguageForm(forms.ModelForm):

    class Meta:
        model = Language
        fields = "__all__"

django_app/sakila/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .forms import *
from .models import *

def act(request):

    if request.method == "POST":
        form = ActorForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/show")
            except:
                pass
    else:
        form = ActorForm()

    return render(request, "index.html", {"form": form})

def show_actor(request):

    actors = Actor.objects.all()
    return render(request, "show.html", {"actors": actors})

def edit_actor(request, id):

    actor = Actor.objects.get(actor_id=id)
    return render(request, "edit.html", {"actor": actor})

def update_actor(request, id):

    actor = Actor.objects.get(actor_id=id)
    form = ActorForm(request.POST, instance=actor)

    if form.is_valid():
        form.save()
        return redirect("/show")

    return render(request, "edit.html", {"actor": actor})

def destroy_actor(request, id):

    actor = Actor.objects.get(actor_id=id)
    actor.delete()
    return redirect("/show")

def flm(request):
    if request.method == "POST":
        form = FilmForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/film_show")
            except:
                pass
        else:
            print(form.errors)
    else:
        form = FilmForm()

    return render(request, "film_index.html", {"form": form})

def show_film(request):
    films = Film.objects.all()
    return render(request, "film_show.html", {"film": films})

def edit_film(request, id):

    film = Film.objects.get(film_id=id)
    return render(request, "film_edit.html", {"film": film})

def update_film(request, id):

    film = Film.objects.get(film_id=id)
    form = FilmForm(request.POST, instance=film)

    if form.is_valid():
        form.save()
        return redirect("/film_show")

    else:
        print(form.errors)

    return render(request, "film_edit.html", {"film": film})

def destroy_film(request, id):

    film = Film.objects.get(film_id=id)
    film.delete()
    return redirect("/film_show")

def flmac(request):
    if request.method == "POST":
        form = FilmActorForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect("/filmactor_show")
            except:
                pass
        else:
            print(form.errors)
    else:
        form = FilmForm()

    return render(request, "filmactor_index.html", {"form": form})

def show_film(request):
    filmactors = FilmActor.objects.all()
    return render(request, "film_show.html", {"film": filmactors})

def edit_film(request, id1, id2):

    filmactor = FilmActor.objects.get(film_id=id)
    return render(request, "filmactor_edit.html", {"film": filmactor})

def update_film(request, id1, id2):

    film = Film.objects.get(film_id=id)
    form = FilmForm(request.POST, instance=film)

    if form.is_valid():
        form.save()
        return redirect("/film_show")

    else:
        print(form.errors)

    return render(request, "film_edit.html", {"film": film})

django_app/sakila/templates/edit.html
    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
        {% load staticfiles %}  
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </head>  
    <body>  
    <form method="POST" class="post-form" action="/update/{{actor.actor_id}}">
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Update Details</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Actor Id:</label>  
        <div class="col-sm-4">  
            <input type="text" name="actor_id" id="id_actor_id" required maxlength="20" value="{{ actor.actor_id }}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">First Name:</label>  
        <div class="col-sm-4">  
            <input type="text" name="first_name" id="id_first_name" required maxlength="100" value="{{ actor.first_name }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Last Name:</label>  
        <div class="col-sm-4">  
            <input type="text" name="last_name" id="id_last_name" required maxlength="254" value="{{ actor.last_name }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Last Update:</label>  
        <div class="col-sm-4">  
            <input type="date" name="last_update" id="id_last_update" required maxlength="15" value="{{ actor.last_update }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Update</button>  
        </div>  
      </div>  
        </div>  
    </form>  
    </body>  
    </html>  

django_app/sakila/templates/film_edit.html
    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>
<<<<<<< HEAD
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

=======
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
>>>>>>> 0a750f2a639ab8da7da5d55edf9328667ebd26ac
    </head>  
    <body>  
    <form method="POST" class="post-form" action="/film_update/{{ film.film_id }}">
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Update Details</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Film Id:</label>  
        <div class="col-sm-4">  
            <input type="text" name="film_id" id="id_film_id" required maxlength="20" value="{{ film.film_id }}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Title:</label>  
        <div class="col-sm-4">  
            <input type="text" name="title" id="id_title" required maxlength="100" value="{{ film.title }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Description:</label>  
        <div class="col-sm-4">  
            <input type="text" name="description" id="id_description" required maxlength="254" value="{{ film.description }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Released:</label>  
        <div class="col-sm-4">  
            <input type="text" name="release_year" id="id_release_year" required maxlength="15" value="{{ film.release_year }}" />
        </div>
        </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Language:</label>  
        <div class="col-sm-4">  
            <input type="text" name="language" id="id_language" required maxlength="15" value="{{ film.language }}" />
        </div>
    </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Rented for:</label>  
        <div class="col-sm-4">  
            <input type="text" name="rental_duration" id="id_rental_duration" required maxlength="15" value="{{ film.rental_duration }}" />
        </div>
    </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Rental rate:</label>  
        <div class="col-sm-4">  
            <input type="text" name="rental_rate" id="id_rental_rate" required maxlength="15" value="{{ film.rental_rate }}" />  
        </div>
    </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Length:</label>  
        <div class="col-sm-4">  
            <input type="text" name="length" id="id_length" required maxlength="15" value="{{ film.length }}" />  
        </div>
    </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Cost:</label>  
        <div class="col-sm-4">  
            <input type="text" name="replacement_cost" id="id_replacement_cost" required maxlength="15" value="{{ film.replacement_cost }}" />  
        </div>  
      </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Rating:</label>  
        <div class="col-sm-4">  
            <input type="text" name="rating" id="id_rating" required maxlength="15" value="{{ film.rating }}" />
        </div>
    </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Special features:</label>  
        <div class="col-sm-4">  
            <input type="text" name="special_features" id="id_special_features" required maxlength="15" value="{{ film.special_features }}" />  
        </div>
    </div>
	<div class="form-group row">  
        <label class="col-sm-2 col-form-label">Last update:</label>  
        <div class="col-sm-4">  
            <input type="date" name="last_update" id="id_last_update" required maxlength="15" value="{{ film.last_update }}" />
        </div>
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>
        <div class="col-sm-4">
        <button type="submit" class="btn btn-success">Update</button>
        </div>
      </div>
    </div>
        </div>
    </form>  
    </body>  
    </html>  

django_app/sakila/templates/film_index.html
    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>  
        {% load staticfiles %}  
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<<<<<<< HEAD
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

=======
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
>>>>>>> 0a750f2a639ab8da7da5d55edf9328667ebd26ac
    </head>  
    <body>  
    <form method="POST" class="post-form" action="/flm">
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Enter Details</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Film Id:</label>  
        <div class="col-sm-4">  
          {{ form.film_id }}  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Title:</label>  
        <div class="col-sm-4">  
          {{ form.title }}  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Description:</label>  
        <div class="col-sm-4">  
          {{ form.description }}  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Released:</label>  
        <div class="col-sm-4">  
          {{ form.release_year }}  
        </div>  
      </div>
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Language:</label>  
        <div class="col-sm-4">  
          {{ form.language }}  
        </div>  
      </div>
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Rented for:</label>  
        <div class="col-sm-4">  
          {{ form.rental_duration }}  
        </div>  
      </div>
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Rental rate:</label>  
        <div class="col-sm-4">  
          {{ form.rental_rate }}  
        </div>  
      </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Length:</label>  
        <div class="col-sm-4">  
          {{ form.length }}  
        </div>  
      </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Replacement cost:</label>  
        <div class="col-sm-4">  
          {{ form.replacement_cost }}  
        </div>  
      </div>
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Rating:</label>  
        <div class="col-sm-4">  
          {{ form.rating }}  
        </div>  
      </div>
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Special features:</label>  
        <div class="col-sm-4">  
          {{ form.special_features }}  
        </div>  
      </div>
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Last updated:</label>  
        <div class="col-sm-4">  
          {{ form.last_update }}  
        </div>  
      </div>    
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-primary">Submit</button>  
        </div>  
      </div>  
        </div>  
    </form>  
    </body>  
    </html>  

django_app/sakila/templates/filmactor_edit.html
    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
    </head>  
    <body>  
    <form method="POST" class="post-form" action="/update/{{filmactor.actor}}">  
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Update Details</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Actor ID:</label>  
        <div class="col-sm-4">  
            <input type="text" name="actor" id="id_actor" required maxlength="20" value="{{ filmactor.actor }}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Film ID:</label>  
        <div class="col-sm-4">  
            <input type="text" name="film" id="id_film" required maxlength="100" value="{{ filmactor.film }}" />  
        </div>  
      </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Last Update:</label>  
        <div class="col-sm-4">  
            <input type="date" name="last_update" id="id_last_update" required maxlength="15" value="{{ filmactor.last_update }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Update</button>  
        </div>  
      </div>  
        </div>  
    </form>  
    </body>  
    </html>  

django_app/sakila/templates/language_edit.html
    <!DOCTYPE html>  
    <html lang="en">  
    <head>  
        <meta charset="UTF-8">  
        <title>Index</title>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>  
    </head>  
    <body>  
    <form method="POST" class="post-form" action="/update/{{language.language_id}}">  
            {% csrf_token %}  
        <div class="container">  
    <br>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <h3>Update Details</h3>  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Lanugage ID:</label>  
        <div class="col-sm-4">  
            <input type="text" name="language_id" id="id_language_id" required maxlength="20" value="{{ language.language_id }}"/>  
        </div>  
      </div>  
      <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Name:</label>  
        <div class="col-sm-4">  
            <input type="text" name="name" id="id_name" required maxlength="50" value="{{ language.name }}" />  
        </div>  
      </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-2 col-form-label">Last Update:</label>  
        <div class="col-sm-4">  
            <input type="date" name="last_update" id="id_last_update" required maxlength="15" value="{{ language.last_update }}" />  
        </div>  
      </div>  
        <div class="form-group row">  
        <label class="col-sm-1 col-form-label"></label>  
        <div class="col-sm-4">  
        <button type="submit" class="btn btn-success">Update</button>  
        </div>  
      </div>  
        </div>  
    </form>  
    </body>  
    </html>  